services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true
    bind:
      $host: '%pumukit_ldap.host%'
      $port: '%pumukit_ldap.port%'
      $version: '%pumukit_ldap.version%'
      $useSSL: '%pumukit_ldap.useSSL%'
      $server: '%pumukit_ldap.server%'
      $bindRdn: '%pumukit_ldap.bind_rdn%'
      $bindPassword: '%pumukit_ldap.bind_password%'
      $baseDn: '%pumukit_ldap.base_dn%'

  Pumukit\LDAPBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  Pumukit\LDAPBundle\Services\LDAPService:
    class: Pumukit\LDAPBundle\Services\LDAPService

  Pumukit\LDAPBundle\EventListener\AuthenticationHandler:
    class: Pumukit\LDAPBundle\EventListener\AuthenticationHandler

  Pumukit\LDAPBundle\Services\LDAPUserService:
    class: Pumukit\LDAPBundle\Services\LDAPUserService
