pumukit_ldap_bundle:
    resource: "@PumukitLDAPBundle/Controller/"
    type:     annotation
    prefix:   /admin/ldap

pumukit_ldap_js:
    pattern: /ldap/ldap.js
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PumukitLDAPBundle::ldap.js.twig'
        _format: js

pumukit_ldap_css:
    pattern: /ldap/ldap.css
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PumukitLDAPBundle::ldap.css.twig'
        _format: css